app/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api import views

router = DefaultRouter()
router.register('licenses', views.LicenseViewSet)
router.register('languages', views.LanguageViewSet)
router.register('services', views.ServiceViewSet)
router.register('disease_conditions', views.DiseaseConditionViewSet)
router.register('body_conditions', views.BodyConditionViewSet)
router.register('citys', views.CityViewSet)
router.register('countys', views.CountyViewSet)
router.register('search_cases', views.CaseSearchViewSet)
router.register('orders', views.OrderViewSet)
router.register('userServiceLocations', views.UserServiceLocationViewSet)
router.register('userWeekDayTimes', views.UserWeekDayTimeViewSet)
router.register('chatroom', views.ChatRoomViewSet)

router.register('system_messages', views.SystemMessageViewSet)
router.register('search_servants', views.SearchServantViewSet)
router.register('recommend_servants', views.RecommendServantViewSet)
router.register('servant_cases', views.ServantCaseViewSet)
router.register('need_cases', views.NeedCaseViewSet)
router.register('reviews', views.ReviewViewSet)
router.register('blog_posts', views.BlogPostViewSet)
router.register('blog_categories', views.BlogCategoryViewSet)
# router.register('choose_servant', views.ChooseServantViewSet)

app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
    path('servant_put_review/<int:pk>', views.ServantPutReviewView.as_view()),
    path('create_case', views.CreateCase.as_view()),
    path('create_servant_order', views.CreateServantOrder.as_view()),
    path('messages', views.MessageViewSet.as_view()),
    path('earlytermination', views.EarlyTermination.as_view()),
    path('edit_case', views.EditCase.as_view()),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/user/', include('user.urls')),
    path('api/', include('api.urls')),
    path('web/', include('web.urls')),
    path('newebpayApi/', include('newebpayApi.urls')),
    path('ezpay_invoice/', include('ezpay_invoice.urls')),
    path('backboard/', include('backboard.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/backboard/urls.py
from django.urls import path, include
from . import views
from django.shortcuts import render
from django.http import HttpResponse

urlpatterns = [
    path('all_cases', views.all_cases, name = 'all_cases'), 
    path('', views.login, name='backboard_login'),
    path('all_members', views.all_members, name = 'all_members'), 
    path('bills', views.bills, name = 'bills'), 
    path('case_detail', views.case_detail, name = 'case_detail'), 
    path('member_detail', views.member_detail, name = 'member_detail'), 
    path('all_blogs', views.all_blogs, name = 'all_blogs'), 
    path('new_blog', views.new_blog, name = 'new_blog'), 
    path('all_categories', views.all_categories, name = 'all_categories'),
    path('new_edit_category', views.new_edit_category, name = 'new_edit_category'),
    path('member_data_review', views.member_data_review, name = 'member_data_review'),
    path('refunds', views.refunds, name = 'refunds'),
    path('logout', views.logout, name='backboard_logout'),
    path('all_assistances', views.all_assistances, name = 'all_assistances'), 
    path('new_assistance', views.new_assistance, name = 'new_assistance'), 
    path('userstore_detail', views.userstore_detail, name = 'userstore_detail'), 
    path('ajax_refresh_county', views.ajax_refresh_county, name = 'ajax_refresh_county'),
    

]

app/newebpayApi/urls.py
from django.urls import path
from newebpayApi import views

app_name = 'newebpayApi'

urlpatterns = [
    path('create_merchant', views.CreateMerchant.as_view(), name='create_merchant'),
    path('mpg_trade', views.MpgTrade.as_view()),
    path('search_tradeinfo', views.SearchTradeInfo.as_view()),
    path('cancel_authorization', views.CancelAuthorization.as_view()),
    path('invoice', views.Invoice.as_view()),
    path('appropriation', views.Appropriation.as_view()),
    path('debit', views.Debit.as_view()),
    path('notifyurl_callback/<int:id>/', views.NotifyUrlCallback.as_view()),

    path('success_pay', views.success_pay, name = 'success_pay'),
]

app/backboard/views.py
from django.shortcuts import render,redirect
from django.core.paginator import Paginator
from django.http import HttpResponse ,JsonResponse ,HttpResponseRedirect ,response
import urllib
import datetime
from newebpayApi import module
import requests
import time
import json
from modelCore.forms import BlogPostCoverImageForm ,AssistancePostCoverImageForm
from modelCore.models import BlogCategory, BlogPost, BlogPostCategoryShip ,Case ,Order ,Review ,Service ,UserServiceShip ,CaseServiceShip
from modelCore.models import OrderIncreaseService, MonthSummary ,User ,UserLicenseShipImage ,License ,AssistancePost ,UserStore ,City ,County
from django.contrib import auth
from django.contrib.auth import authenticate

def ajax_refresh_county(request):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest' and request.POST['action'] == 'refresh_county':
        updatedData = urllib.parse.parse_qs(request.body.decode('utf-8'))
        # print(updatedData)
        city_id = updatedData['city_id'][0]
        counties = County.objects.filter(city=City.objects.get(id=city_id))
        # countylist = serializers.serialize('json', list(counties))
        data=[]
        for county in counties:
            item = {
                'id':county.id,
                'county':county.name,
            }
            data.append(item)
        # print(data)
        return JsonResponse({'data':data})

def login(request):
    if request.method == 'POST':
        phone = request.POST['phone']
        password = request.POST['password']
        user = authenticate(request, phone=phone, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/backboard/all_cases')
        else:
            return redirect('/backboard/')

    return render(request, 'backboard/login.html')

def logout(request):
    auth.logout(request)
    return redirect('/backboard/')

def all_cases(request):
    if not request.user.is_authenticated or not request.user.is_staff:
        return redirect('/backboard/')

    cases = Case.objects.all()
    state = request.GET.get('state')
    if state != None:
        cases = cases.filter(state=state)
    paginator = Paginator(cases, 10)
    if request.GET.get('page') != None:
        page_number = request.GET.get('page') 
    else:
        page_number = 1
    page_obj = paginator.get_page(page_number)

    page_obj.adjusted_elided_pages = paginator.get_elided_page_range(page_number)
    return render(request, 'backboard/all_cases.html',{'cases':page_obj})

def all_members(request):
    if not request.user.is_authenticated or not request.user.is_staff:
        return redirect('/backboard/')

    users = User.objects.filter(is_staff=False)
    members_num = users.count()
    needers_num = users.filter(is_servant_passed=False).count()
    servants_num = users.filter(is_servant_passed=True).count()
    apply_servant_num = users.filter(is_apply_servant=True,is_servant_passed=False).count()
    member = request.GET.get('member')
    if member == 'needer':
        users = users.filter(is_servant_passed=False)
    elif member == 'servant':
        users = users.filter(is_servant_passed=True)
    elif member == 'apply_servant':
        users = users.filter(is_apply_servant=True,is_servant_passed=False)
    paginator = Paginator(users, 10)
    if request.GET.get('page') != None:
        page_number = request.GET.get('page') 
    else:
        page_number = 1
    page_obj = paginator.get_page(page_number)

    page_obj.adjusted_elided_pages = paginator.get_elided_page_range(page_number)
    return render(request, 'backboard/all_members.html',{'users':page_obj,'members_num':members_num,'needers_num':needers_num,'servants_num':servants_num,'apply_servant_num':apply_servant_num})

def bills(request):
    if not request.user.is_authenticated or not request.user.is_staff:
        return redirect('/backboard/')
    
    # summarys = MonthSummary.objects.all().order_by('-id')[:2]
    summarys = MonthSummary.objects.all().order_by('-month_date')[:2]
    this_month_day = summarys[0].month_date
    last_month_day = this_month_day - datetime.timedelta(days=30)

    return render(request, 'backboard/bills.html', {'summarys':summarys,  'this_month_day':this_month_day, 'last_month_day':last_month_day})

def case_detail(request):
    if not request.user.is_authenticated or not request.user.is_staff:
        return redirect('/backboard/')

    case_id = request.GET.get('case')
    case = Case.objects.get(id=case_id)
    order = Order.objects.get(case=case)
    # review = Review.objects.get(case=case)
    order_increase_services = OrderIncreaseService.objects.filter(order=order)

    return render(request, 'backboard/case_detail.html',{'order_increase_services':order_increase_services, 'case':case,'order':order, 'order_increase_services':order_increase_services})

def member_detail(request):
    if not request.user.is_authenticated or not request.user.is_staff:
        return redirect('/backboard/')

    user_id = request.GET.get('user')
    user = User.objects.get(id=user_id)
    offend_orders = Order.objects.filter(user=user)
    take_orders = Order.objects.filter(servant=user)
    if request.method == 'POST' and 'reset_password' in request.POST :
        password = "00000"
        user.set_password(password)
        user.save()
    return render(request, 'backboard/member_detail.html',{'user':user,'offend_orders':offend_orders,'take_orders':take_orders})


def all_blogs(request):
    if not request.user.is_authenticated or not request.user.is_staff:
        return redirect('/backboard/')

    if request.GET.get('delete_id') != None:
        BlogPost.objects.get(id=request.GET.get('delete_id')).delete()

    blogPosts = BlogPost.objects.all().order_by('-id')

    paginator = Paginator(blogPosts, 20)
    if request.GET.get('page') != None:
        page_number = request.GET.get('page') 
    else:
        page_number = 1
    page_obj = paginator.get_page(page_number)

    page_obj.adjusted_elided_pages = paginator.get_elided_page_range(page_number)

    return render(request, 'backboard/all_blogs.html', {'blogPosts':page_obj})

# edit 跟 new 同一頁
def new_blog(request):
    if not request.user.is_authenticated or not request.user.is_staff:
        return redirect('/backboard/')

    categories = BlogCategory.objects.all()

    if request.method == 'POST':
        
        if request.GET.get('post_id') != None:
            blogPost = BlogPost.objects.get(id=request.GET.get('post_id'))
        else:
            blogPost = BlogPost()
            blogPost.create_date = datetime.datetime.now()

        blogPost.title = request.POST.get('title') 
        blogPost.body = request.POST.get('body') 
        blogPost.state = request.POST.get('post')
        
        if blogPost.state == 'publish':
            blogPost.publish_date = datetime.datetime.now()
        
        if blogPost.title != None and blogPost.title != '':

            if request.FILES.get('cover_image', False):
                blogPost.cover_image = request.FILES['cover_image']

            blogPost.save()

            for category in categories:
                if request.POST.get(f'check_category_{category.id}') != None:
                    BlogPostCategoryShip.objects.create(post=blogPost, category=category)

            # if request.FILES.get('cover_image', False):
            #     form = BlogPostCoverImageForm(request.POST, request.FILES)
            #     form.instance = 
            #     form.save()
            # else:
            #     print("no new file, do nothing")

        return redirect('all_blogs')

    if request.GET.get('post_id') != None:
        blogPost = BlogPost.objects.get(id=request.GET.get('post_id'))
        form = BlogPostCoverImageForm(instance=blogPost)
        category_ids = list(BlogPostCategoryShip.objects.filter(post=blogPost).values_list('category', flat=True))
        checkedCatories = BlogCategory.objects.filter(id__in=category_ids)
        return render(request, 'backboard/new_blog.html', {'categories':categories, 'post':blogPost, 'checkedCatories':checkedCatories, 'form':form})

    form = BlogPostCoverImageForm()
    return render(request, 'backboard/new_blog.html', {'categories':categories, 'form':form})

def all_categories(request):
    if not request.user.is_authenticated or not request.user.is_staff:
        return redirect('/backboard/')

    if request.GET.get('delete_id') != None:
        try:
            BlogCategory.objects.get(id=request.GET.get('delete_id')).delete()
        except:
            print("no such category")

    categories = BlogCategory.objects.all()
    return render(request, 'backboard/all_categories.html', {'categories':categories})

def new_edit_category(request):
    if not request.user.is_authenticated or not request.user.is_staff:
        return redirect('/backboard/')

    if request.method == 'POST':
        if request.POST.get('post') == 'save':
            if request.POST.get('name') != None and request.POST.get('name') != '':
                if request.GET.get('category_id') != None:
                    category = BlogCategory.objects.get(id=request.GET.get('category_id'))
                    category.name = request.POST.get('name')
                    category.save()
                else:
                    BlogCategory.objects.create(name=request.POST.get('name'))
        return redirect('all_categories')

    if request.GET.get('category_id') != None:
        category = BlogCategory.objects.get(id=request.GET.get('category_id'))
        return render(request, 'backboard/new_edit_category.html', {'category':category})

    return render(request, 'backboard/new_edit_category.html')

def member_data_review(request):
    if not request.user.is_authenticated or not request.user.is_staff:
        return redirect('/backboard/')

    user_id = request.GET.get('user')
    user = User.objects.get(id=user_id)
    licences = License.objects.all().order_by('id')

app/backboard/templates/backboard/all_assistances.html
{% extends 'backboard/base.html' %} {% block content %}
{% load static %}

<!-- 內容 -->
  <div class="mb-3">
    <div class="col-lg-12 ps-lg-2 mb-3">
      <div class="card h-lg-100">
        <div class="card-header">
  
          <div class="mb-3 d-flex justify-content-between">
            問答列表
            <a class="custom-purple-btn text-white btn-sm " href="{% url 'new_assistance' %}">新增問答</a>
          </div>
                    
          <div id="tableExample2" data-list='{"valueNames":["name","email","age"],"page":10,"pagination":true}'>
            <div class="table-responsive scrollbar">
              <table class="table  table-striped fs--1 mb-0">
                <div class="border border-1"></div>
                <thead>
                  <tr>
                    <th scope="col">問答標題</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody class="list">
                  {% for post in assistancePosts %}
                    <tr>
                      <td>{{post.title}}</td>
                      <td class="alnright">                    
                        <a class="custom-purple-btn text-white btn-sm " href="{% url 'new_assistance' %}?post_id={{post.id}}">編輯</a>
                        <a class="bg-danger text-white btn-sm" href="{% url 'all_assistances' %}?delete_id={{post.id}}" >刪除</a>
                      </td>
                    </tr> 
                  {% endfor %}
                </tbody>
              </table>
            </div>

            <br>
            <div class="text-center">
              {% for page_number in blogPosts.adjusted_elided_pages %} 
                {% if page_number == blogPosts.paginator.ELLIPSIS %} 
                  {{page_number}} 
                {% else %}
                  <a href="?page={{page_number}}" class="{% if page_number == blogPosts.number %}current{% endif %}">&nbsp;&nbsp;{{page_number}}&nbsp;&nbsp;</a>
                {% endif %} 
              {% endfor %}
            </div>

          </div>

        </div>
      </div>
    </div>
  </div> 
        
{% endblock %}

app/backboard/templates/backboard/all_blogs.html
{% extends 'backboard/base.html' %} {% block content %}
{% load static %}

<!-- 內容 -->
  <div class="mb-3">
    <div class="col-lg-12 ps-lg-2 mb-3">
      <div class="card h-lg-100">
        <div class="card-header">
  
          <div class="mb-3 d-flex justify-content-between">
            文章列表
            <a class="custom-purple-btn text-white btn-sm " href="{% url 'new_blog' %}">新增文章</a>
          </div>
                    
          <div id="tableExample2" data-list='{"valueNames":["name","email","age"],"page":10,"pagination":true}'>
            <div class="table-responsive scrollbar">
              <table class="table  table-striped fs--1 mb-0">
                <div class="border border-1"></div>
                <thead>
                  <tr>
                    <th scope="col">發布狀態</th>
                    <th scope="col">文章標題</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody class="list">
                  {% for post in blogPosts %}
                    <tr>
                      <td >
                        {% if post.state == 'draft' %}
                          <button type="button" class="custom-grey-border-btn btn-sm" disabled>草稿</button>
                        {% else %}
                          <button type="button" class="custom-grey-border-btn btn-sm" disabled>已發布</button>
                        {% endif %}
                      </td>
                      <td>{{post.title}}</td>
                      <td class="alnright">                    
                        <a class="custom-purple-btn text-white btn-sm " href="{% url 'new_blog' %}?post_id={{post.id}}">編輯</a>
                        <a class="bg-danger text-white btn-sm" href="{% url 'all_blogs' %}?delete_id={{post.id}}" >刪除</a>
                      </td>
                    </tr> 
                  {% endfor %}
                </tbody>
              </table>
            </div>

            <br>
            <div class="text-center">
              {% for page_number in blogPosts.adjusted_elided_pages %} 
                {% if page_number == blogPosts.paginator.ELLIPSIS %} 
                  {{page_number}} 
                {% else %}
                  <a href="?page={{page_number}}" class="{% if page_number == blogPosts.number %}current{% endif %}">&nbsp;&nbsp;{{page_number}}&nbsp;&nbsp;</a>
                {% endif %} 
              {% endfor %}
            </div>

          </div>

        </div>
      </div>
    </div>
  </div> 
        
{% endblock %}

app/backboard/templates/backboard/all_categories.html
{% extends 'backboard/base.html' %} {% block content %}
{% load static %}

<!-- 內容 -->
  <div class="mb-3">
    <div class="col-lg-12 ps-lg-2 mb-3">
      <div class="card h-lg-100">
        <div class="card-header">
  
          <div class="mb-3 d-flex justify-content-between">
            所有文章類別
            <a class="text-right custom-purple-btn text-white btn-sm " href="{% url 'new_edit_category' %}">新增類別</a>
          </div>
                    
          <div id="tableExample2" data-list='{"valueNames":["name","email","age"],"page":10,"pagination":true}'>
            <div class="table-responsive scrollbar">
              <table class="table  table-striped fs--1 mb-0">
                <div class="border border-1"></div>
                <thead>
                  <tr>
                    <th scope="col">分類名稱</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody class="list">
                  {% for category in categories %}
                    <tr>
                      <td>{{category.name}}</td>
                      <td class="alnright">                    
                        <a class="custom-purple-btn text-white btn-sm " href="{% url 'new_edit_category' %}?category_id={{category.id}}">編輯類別</a>
                        <a class="bg-danger text-white btn-sm" href="{% url 'all_categories' %}?delete_id={{category.id}}" >刪除</a>
                      </td>
                    </tr> 
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <br>
            <div class="d-flex justify-content-center mt-3">
              <button class="btn btn-sm btn-chijia-default me-1" type="button" title="Previous" data-list-pagination="prev"><span class="fas fa-chevron-left"></span></button>
              <ul class="pagination mb-0"></ul>
              <button class="btn btn-sm btn-chijia-default ms-1" type="button" title="Next" data-list-pagination="next"><span class="fas fa-chevron-right"> </span></button>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div> 
        
{% endblock %}

app/backboard/templates/backboard/bills.html
{% extends 'backboard/base.html' %} {% block content %}
{% load static %}

<!-- 內容 -->
<div class="mb-3">
  <div class="col-lg-12 ps-lg-2 mb-3">
    <div class="card h-lg-100">
      <div class="card-header">
        <div class="mb-3">
          本月統計( {{this_month_day.year }} / {{this_month_day.month}} )
        </div>
        <table class="table">
          <thead class="bill-thead">
            <tr>
              <th scope="col">訂單金額</th>
              <th scope="col">取消金額</th>
              <th scope="col">實際請款金額</th>
              <th scope="col">退款金額</th>
              <th scope="col">平台入帳金額</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="text-nowrap">{{ summarys.0.month_revenue }}</td>
              <td class="text-nowrap">{{ summarys.0.month_cancel_amount }}</td>
              <td class="text-nowrap">{{ summarys.0.month_pay_amount }}</td>
              <td class="text-nowrap">{{ summarys.0.month_refound_amount }}</td>
              <td class="text-nowrap">{{ summarys.0.month_platform_revenue }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="card-header">
        <div class="mb-3">
          上月統計( {{ last_month_day.year }} / {{ last_month_day.month }} )
        </div>
        <table class="table">
          <thead class="bill-thead">
            <tr>
              <th scope="col">訂單金額</th>
              <th scope="col">取消金額</th>
              <th scope="col">實際請款金額</th>
              <th scope="col">退款金額</th>
              <th scope="col">平台入帳金額</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="text-nowrap">{{ summarys.1.month_revenue }}</td>
              <td class="text-nowrap">{{ summarys.1.month_cancel_amount }}</td>
              <td class="text-nowrap">{{ summarys.1.month_pay_amount }}</td>
              <td class="text-nowrap">{{ summarys.1.month_refound_amount }}</td>
              <td class="text-nowrap">{{ summarys.1.month_platform_revenue }}</td>
             </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div> 

{% endblock %}

app/backboard/templates/backboard/userstore_detail.html
{% extends 'backboard/base.html' %} {% block content %}
{% load static %}

<!-- 內容 -->
<div class="mb-3">
  <div class="col-lg-12 ps-lg-2 mb-3">

     <!-- 會員資訊 -->
    <div class="card h-lg-100 mb-5">
      <div class="card-header mb-2">

        <div class="h5 mb-3">
          <b>會員資訊 --- 申請藍新商店</b>
        </div>
        <div class="border"></div>
        <form method="post" enctype="multipart/form-data" action={% url 'newebpayApi:create_merchant' %} >{% csrf_token %}
            <div class="d-flex justify-content-between mt-3">
            <div>
                <span>姓名：{{user.name}}</span>
                <span class="mx-3">電話：{{user.phone}}</span>
                <input type="hidden" id="user_id" name="user_id" value={{user.id}}>
            </div>
            <div>
                <button class="btn btn-success  btn-sm" type="submit" name="cancel" value='draft'>取消</button>
                <button class="btn btn-primary btn-sm" type="submit" name="post" value='publish'>送出申請</button>
            </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-6 col-8">
                    {% for userLicenseImage in userLicenseImages %}
                    <div class="mt-3 d-flex align-items-center ">  
                        <div class="container" >
                            {% if userLicenseImage.image.url != None %}
                                <img class="img-fluid rounded" src="{{userLicenseImage.image.url}}" alt="" width="300px" />
                            {% else %}
                                <div style="background-color:#d4d1cb;width: 300px;height: 200px;" ></div>
                                <div class="centered">{{userLicenseImage.license}}</div>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                    <br>
                </div>
                <div class="col-md-6 col-8">
                    <div>身分證姓名</div>
                    <div>
                        <label class="h6 mt-2" for="aboriginal"></label>
                        <input class="booking-input" style="width: 300px;" id="aboriginal" name="ID_card_name"  type="text" placeholder="" />
                    </div><br>
                    <div>英文姓名</div>
                    <div>
                        <label class="h6 mt-2" for="aboriginal"></label>
                        <input class="booking-input" style="width: 300px;" id="aboriginal" name="ManagerNameE"  type="text" placeholder="" />
                    </div><br>
                    <div>身分證號</div>
                    <div>
                        <label class="h6 mt-2" for="aboriginal"></label>
                        <input class="booking-input" style="width: 300px;" id="aboriginal" name="ID_number"  type="text" placeholder="" />
                    </div><br>
                    <div>出生年月日</div>
                    <div>
                        <label class="h6 mt-2" for="aboriginal"></label>
                        <input class="booking-input" style="width: 300px;" id="aboriginal" name="birthday"  type="text" placeholder="ex.20200103" />
                    </div><br>
                    <div>身份證發證日期</div>
                    <div>
                        <label class="h6 mt-2" for="aboriginal"></label>
                        <input class="booking-input" style="width: 300px;" id="aboriginal" name="ID_card_date"  type="text" placeholder="ex.1070124" />
                    </div><br>
                    <div>身分證領補換</div>
                    <div class="mt-1 btn-group">
                        <select class="dropdown-button" id="IDFrom" name="IDFrom"  select>
                            <option style="text-align: center" name="IDFrom" value="1" >初發</option>
                            <option style="text-align: center" name="IDFrom" value="2" >補發</option>
                            <option style="text-align: center" name="IDFrom" value="3" >換發</option>
                            <!-- <option value="醫院看護">醫院看護</option> -->
                        </select>
                    </div><br><br>
                    <div>城市</div>
                    <div class="mt-1 btn-group">
                        <select class="dropdown-button" id="city_select" name="city_id" onchange="listCities()" select>
                        
                        {% for city in citys %}
                            <option style="text-align: center" name="city_option" value="{{city.id}}" {% if city == cityName %} selected="selected" {% endif %}>{{city}}</option>
                            <!-- <option value="醫院看護">醫院看護</option> -->
                        {% endfor %}
                        </select>
                    </div><br><br>
                    <div>區域</div>
                    <div class="mt-1 btn-group">
                        <select class="dropdown-button" id="county_select" name="county_id" >
                            <option style="text-align: center" value="全區">全區</option>
                            {% for county in counties %}
                            <option style="text-align: center" name="county_option" value="{{county.id}}" {% if county == countyName %} selected="selected" {% endif %}>{{county}}</option>
                            {% endfor %}
                        </select>
                    </div><br><br>

                    <div>地址</div>
                    <div>
                        <label class="h6 mt-2" for="aboriginal"></label>
                        <input class="booking-input" style="width: 300px;" id="aboriginal" name="MerchantAddr"  type="text" placeholder="xx路xx號" />
                    </div><br>
                    <div>英文地址</div>
                    <div>
                        <label class="h6 mt-2" for="aboriginal"></label>
                        <input class="booking-input" style="width: 300px;" id="aboriginal" name="MerchantEnAddr"  type="text" placeholder="" />
                    </div><br>
                </div>
            </div>
        </form>
      </div>
    </div>
  </div>
</div> 
<style>
    .container {
        position: relative;
        color: black;
        /* background-color: gray; */
        }
    .centered {
        position: absolute;
        top: 50%;
        left: 150px;
        transform: translate(-50%, -50%);
        }
</style>
<script>
    function getCookie(name){
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
                  }
              }
          }
          return cookieValue;
      }
    const csrftoken = getCookie('csrftoken');
    function listCities(){
      var cityid = document.getElementById('city_select').value;
      document.getElementById('county_select').innerHTML = '';
      console.log(cityid)
      $.ajax({
        type: "POST",
        data: {'city_id':cityid,
                'action':'refresh_county'},
        headers: {'X-CSRFToken': csrftoken},
        url: "{% url 'ajax_refresh_county' %}",
        success: function(response)
        {
          const data = response.data
          console.log(data)
          // var resultObj = JSON.parse(response);
          var dataHandler = $("#county_select");
          data.forEach(el =>
          {
              var newRow = `<option style="text-align: center" value=${el.id}>${el.county}</option>`;
              dataHandler.append(newRow);
          });

        }
      });
    }
</script>
{% endblock %}