app/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api import views

router = DefaultRouter()
router.register('licenses', views.LicenseViewSet)
router.register('languages', views.LanguageViewSet)
router.register('services', views.ServiceViewSet)
router.register('disease_conditions', views.DiseaseConditionViewSet)
router.register('body_conditions', views.BodyConditionViewSet)
router.register('citys', views.CityViewSet)
router.register('countys', views.CountyViewSet)
router.register('search_cases', views.CaseSearchViewSet)
router.register('orders', views.OrderViewSet)
router.register('userServiceLocations', views.UserServiceLocationViewSet)
router.register('userWeekDayTimes', views.UserWeekDayTimeViewSet)
router.register('chatroom', views.ChatRoomViewSet)

router.register('system_messages', views.SystemMessageViewSet)
router.register('search_servants', views.SearchServantViewSet)
router.register('recommend_servants', views.RecommendServantViewSet)
router.register('servant_cases', views.ServantCaseViewSet)
router.register('need_cases', views.NeedCaseViewSet)
router.register('reviews', views.ReviewViewSet)
router.register('blog_posts', views.BlogPostViewSet)
router.register('blog_categories', views.BlogCategoryViewSet)
# router.register('choose_servant', views.ChooseServantViewSet)

app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
    path('servant_put_review/<int:pk>', views.ServantPutReviewView.as_view()),
    path('create_case', views.CreateCase.as_view()),
    path('create_servant_order', views.CreateServantOrder.as_view()),
    path('messages', views.MessageViewSet.as_view()),
    path('earlytermination', views.EarlyTermination.as_view()),
    path('edit_case', views.EditCase.as_view()),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/user/', include('user.urls')),
    path('api/', include('api.urls')),
    path('web/', include('web.urls')),
    path('newebpayApi/', include('newebpayApi.urls')),
    path('ezpay_invoice/', include('ezpay_invoice.urls')),
    path('backboard/', include('backboard.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/modelCore/models.py
import pathlib
from unicodedata import category
import uuid
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.forms import FloatField
from django.urls import reverse
from django.db.models import Avg ,Sum 
from ckeditor_uploader.fields import RichTextUploadingField

def image_upload_handler(instance,filename):
    fpath = pathlib.Path(filename)
    new_fname = str(uuid.uuid1()) #uuid1 -> uuid + timestamp
    return f'images/{new_fname}{fpath.suffix}'

@property
def get_photo_url(self):
    if self.photo and hasattr(self.photo, 'url'):
        return self.photo.url
    else:
        return "/static/web/assets/img/generic/2.jpg"
class UserManager(BaseUserManager):

    def create_user(self, phone, password=None, **extra_fields):
        """Creates and saves a new user"""
        if not phone:
            raise ValueError('Users must have an phone')
        # user = self.model(email=self.normalize_email(email), **extra_fields)
        user = self.model(
            phone = phone, 
            name=extra_fields.get('name'),
            line_id=extra_fields.get('line_id'),
            apple_id =extra_fields.get('apple_id'),
        )
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, phone, password, **extra_fields):
        """Creates and saves a new super user"""
        user = self.create_user(phone, password, **extra_fields)

        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)

        return user

class User(AbstractBaseUser, PermissionsMixin):
    phone = models.CharField(max_length=10, unique=True)
    objects = UserManager()
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    name = models.CharField(max_length=255)

    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES,default=MALE)

    email = models.CharField(max_length= 100, blank = True, null=True)
    address = models.CharField(max_length= 100, blank = True, null=True)
    image = models.ImageField(upload_to=image_upload_handler, blank=True, null=True)

    line_id = models.CharField(max_length= 100, blank = True, null=True, unique=True)
    apple_id = models.CharField(max_length= 100, blank = True, null=True, unique=True)

    # is_apply_servant == True => 已提交, 審核中
    # is_apply_servant == False => 未提交, or 需重新提交
    is_apply_servant = models.BooleanField(default=False) 
    is_servant_passed = models.BooleanField(default=False)
    is_fcm_notify = models.BooleanField(default=True)

    is_home = models.BooleanField(default=False)
    home_hour_wage = models.IntegerField(default=0, blank = True, null=True)
    home_half_day_wage = models.IntegerField(default=0, blank = True, null=True)
    home_one_day_wage = models.IntegerField(default=0, blank = True, null=True)
    
    is_hospital = models.BooleanField(default=False)
    hospital_hour_wage = models.IntegerField(default=0, blank = True, null=True)
    hospital_half_day_wage = models.IntegerField(default=0, blank = True, null=True)
    hospital_one_day_wage = models.IntegerField(default=0, blank = True, null=True)

    about_me = models.TextField(default='', blank = True, null=True)
    is_continuous_time = models.BooleanField(default=True)
    is_continuous_start_time = models.FloatField(default=0, blank=True, null=True)
    is_continuous_end_time = models.FloatField(default=24, blank=True, null=True)

    background_image = models.ImageField(upload_to=image_upload_handler, blank=True, null=True)

    ATMInfoBankCode = models.CharField(max_length=20, default='', blank = True, null=True)
    ATMInfoBranchBankCode = models.CharField(max_length=20, default='', blank = True, null=True)
    ATMInfoAccount = models.CharField(max_length=20, default='', blank = True, null=True)

    USERNAME_FIELD = 'phone'

    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)
        licenses = License.objects.all()
        print(licenses)
        print('user',self)
        for license in licenses:
            if UserLicenseShipImage.objects.filter(user=self,license=license).count() == 0:
                instance = UserLicenseShipImage.objects.create(user=self,license=license)
                print(instance)

    @property
    def needer_avg_rating(self):
        avg_rating = Review.objects.filter(case__user=self,case_offender_rating__gte=1).aggregate(Avg('case_offender_rating'))['case_offender_rating__avg']
        if avg_rating != None:
            return round(avg_rating,1)
        else:
            return 0

    @property
    def needer_avg_rate_range(self):
        if Review.objects.filter(case__user=self,case_offender_rating__gte=1).count() > 0:
            avg_rating = Review.objects.filter(case__user=self,case_offender_rating__gte=1).aggregate(Avg('case_offender_rating'))['case_offender_rating__avg']
            return range(int(avg_rating))
        else:
            return range(0)

    @property
    def needer_avg_rating_is_half_star(self):
        if Review.objects.filter(case__user=self,case_offender_rating__gte=1).count() > 0:
            avg_rating = Review.objects.filter(case__user=self,case_offender_rating__gte=1).aggregate(Avg('case_offender_rating'))['case_offender_rating__avg']
            if (avg_rating -int(avg_rating)) >= 0.5:
            # 判斷
                return True
            else:
                return False
        else:
            return False

    @property
    def needer_avg_rating_empty_star_range(self):
        if Review.objects.filter(case__user=self,case_offender_rating__gte=1).count() > 0:
            avg_rating = Review.objects.filter(case__user=self,case_offender_rating__gte=1).aggregate(Avg('case_offender_rating'))['case_offender_rating__avg']
            if (avg_rating -int(avg_rating)) >= 0.5:
                return range(4-int(avg_rating))
            else:
                return range(5-int(avg_rating))
        else:
            return range(5)

    @property
    def needer_rate_nums(self):
        return Review.objects.filter(case__user=self,case_offender_rating__gte=1).count()

    @property
    def servant_avg_rating(self):
        servant_avg_rating = Review.objects.filter(servant=self,servant_rating__gte=1).aggregate(Avg('servant_rating'))['servant_rating__avg']
        if servant_avg_rating != None:
            return round(servant_avg_rating,1)
        else:
            return 0
    
    @property
    def servant_avg_rate_range(self):
        if Review.objects.filter(servant=self,servant_rating__gte=1).count() > 0:
            avg_rating = Review.objects.filter(servant=self,servant_rating__gte=1).aggregate(Avg('servant_rating'))['servant_rating__avg']
            return range(int(avg_rating))
        else:
            return range(0)

    @property
    def servant_avg_rating_is_half_star(self):
        if Review.objects.filter(servant=self,servant_rating__gte=1).count() > 0:
            avg_rating = Review.objects.filter(servant=self,servant_rating__gte=1).aggregate(Avg('servant_rating'))['servant_rating__avg']
            if (avg_rating -int(avg_rating)) >= 0.5:
            # 判斷
                return True
            else:
                return False
        else:
            return False

    @property
    def servant_avg_rating_empty_star_range(self):
        if Review.objects.filter(servant=self,servant_rating__gte=1).count() > 0:
            avg_rating = Review.objects.filter(servant=self,servant_rating__gte=1).aggregate(Avg('servant_rating'))['servant_rating__avg']
            if (avg_rating -int(avg_rating)) >= 0.5:
                return range(4-int(avg_rating))
            else:
                return range(5-int(avg_rating))
        else:
            return range(5)
    @property
    def servant_rate_nums(self):
        return Review.objects.filter(servant=self,servant_rating__gte=1).count()

class Service(models.Model):
    name = models.CharField(max_length= 100, unique=True)
    remark = models.CharField(max_length= 150, blank = True, null=True)
    is_increase_price = models.BooleanField(default=False)
    

    def __str__(self):
        return self.name

class UserWeekDayTime(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='user_weekday'
    )
    WEEKDAY_CHOICES = [
        ('0', 'Sunday'),
        ('1', 'Monday'),
        ('2', 'Tuesday'),
        ('3', 'Wednesday'),
        ('4', 'Thursday'),
        ('5', 'Friday'),
        ('6', 'Saturday'),
    ]
    weekday = models.CharField(max_length=1, choices=WEEKDAY_CHOICES,)

    start_time = models.FloatField(default=0, blank=True, null=True)
    end_time = models.FloatField(default=24, blank=True, null=True)

    start_time_hour = models.IntegerField(default=8, blank=True, null=True)
    start_time_min = models.IntegerField(default=0, blank=True, null=True)

    end_time_hour = models.IntegerField(default=17, blank=True, null=True)
    end_time_min = models.IntegerField(default=0, blank=True, null=True)

class UserServiceShip(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='ship_services',
    )
    service = models.ForeignKey(
        Service,
        on_delete=models.RESTRICT,
        related_name='service_ships'
    )
    increase_percent = models.FloatField(default=0, blank = True, null=True)
    
class Language(models.Model):
    name = models.CharField(max_length= 100)
    def __str__(self):
        return self.name

class UserLanguage(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='user_languages'
    )
    language =  models.ForeignKey(
        Language,
        on_delete=models.RESTRICT
    )

app/web/templates/web/my/booking_detail.html
{% extends 'web/base.html' %} {% block content %}
{% load static %}
<!-- main -->
<main class="main bg-white" id="top" >

  <div class="container pt-5">
    <div class="row">
      <div class="col-12 col-md-6 ">
              
        <p class="small-section-title-purple mt-2">需求基本資訊</p>
        <div class="case-info-font">
                  <p>照顧者：{{order.servant.name}}</p>
                  <p>案件類型：{% if order.case.care_type == 'home' %}居家照顧{% else %}醫院看護{% endif %}</p>
                  <p>案件地點：{{order.case.city}} </p>
                  <p class="text-indent-5" >案件時間：{% if order.case.is_continuous_time == True %}連續時間{% else %}指定時段{% endif %}<br>2022/04/18 晚上 8:00 ~ 2022/04/22 晚上 8:00</p>
                  <p>給業主的評價：{{review.case_offender_comment}}</p>
        </div>

        <p class="small-section-title-purple mt-5">被照顧者資訊</p>
        <div class="case-info-font">
                  <p>性別：{% if order.case.gender == 'F' %}女{% else %}男{% endif %}</p>
                  <p>體重：{{order.case.weight}}</p>
                  <p>年齡：{{order.case.age}}</p>
                  <p>疾病：{% for casedisease in order.case.case_diseases.all %} {{casedisease.disease}} {% endfor %}</p>
                  <p>補充說明：{{order.case.disease_remark}}</p>
                  <p>身體狀況：{% for casebodycondition in order.case.case_body_conditions.all %} {{casebodycondition.body_condition}} {% endfor %}</p>
                  <p class="text-indent-5">補充說明：{{order.case.conditions_remark}}</p>
        </div>

        <p class="small-section-title-purple mt-5">需求服務項目</p>
        <div class="case-info-font mb-5">
          {% for caseservice in order.case.case_services.all %}
            <p>
              <span class="fas fa-check-circle fs-1" style="color: 55D9A0;"></span>
              {{caseservice.service}}
            </p>
          {% endfor %}
        </div>

      </div>
      <div class="col-12 col-md-6 ">
        <p class="small-section-title-purple mt-2">服務費用</p>
        <div class="section-bg-grey">
                  <span class="case-info-font"><strong>基本費用</strong></span>
                  <div class="row case-info-font">
                    <div class="col-8">
                      ${% if order.case.care_type == 'home' %}{{order.servant.home_hour_wage}}{% else %}{{order.servant.hospital_hour_wage}}{% endif %}x{{work_hours}}小時
                    </div>
                    <div class="col text-end">
                      $ {{order.base_money}}
                    </div>
                  </div>
                  <br>
                  <span class="case-info-font"><strong>加價項目</strong></span>
                  {% for increase_service in order.order_increase_services.all %}
                  <div class="row case-info-font">
                    <div class="col-9">
                      {{increase_service.service}}
                      &emsp;每小時加 {{increase_service.increase_percent}}% x {{work_hours}}小時
                    </div>
                    <div class="col text-end">
                      
                      $ {{increase_service.increase_money}}
                      <br>
                    </div>
                    
                  </div>
                  {% endfor %}
                  <hr>
                  <div class="row">
                    <div class="col-8 case-info-font">
                      <strong>總計</strong>
                    </div>
                    <div class="col text-end " style="color: red;">
                      <strong>$ {{order.total_money}}</strong> 
                    </div>
                  </div>


        </div>

        <!-- 如果 已給 照顧者評價會顯示這個 -->
        <p class="small-section-title-purple mt-4">我給照顧者的評價</p>
        <div class="col align-self-center text-front" style="color: yellow;">
          {% for i in review.servant_rating_range %}
            <span class="fas fa-star" ></span>
          {% endfor %}
          {% if review.servant_rating_is_half_star == True %}
            <span class="fas fa-star-half-alt" ></span>
          {% endif %}
          {% for i in review.servant_rating_empty_star_range %}
            <i class="fa-regular fa-star"></i>  
          {% endfor %}
        </div>
        <div class="case-info-font section-bg-grey">
                  <!-- <img src="/assets/img/new/Star.png" alt="">
                  <img src="/assets/img/new/Star.png" alt="">
                  <img src="/assets/img/new/Star.png" alt="">
                  <img src="/assets/img/new/Star.png" alt="">
                  <img src="/assets/img/new/Star.png" alt=""> -->
                  
                  <p>“ {{review.servant_comment}} “</p>
                  
        </div>

        <!-- 如果 還沒給 照顧者評價會顯示這個 -->
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <p class="small-section-title-purple mt-4">我給照顧者的評價</p>
        <div class="case-info-font">
          <p>我給照顧者幾顆星：</p>
          <div id='myRater' class="d-block"></div>
          <input type="hidden" id="myInput" name="myInput" value="0">
          <p>請輸入給照顧者的評價(150字以內)：</p>
          <textarea class="custom-form-control" id="exampleFormControlTextarea1" name="comment" rows="3"></textarea>
          <div class="d-flex mb-3 flex-row-reverse">
            <button class="small-green-button mt-3 float-right" type="submit">送出</button>
          </div>
        </div>
        </form>
      </div>
    </div>
  </div>
     
</main>
{% endblock %}

app/web/templates/web/my/bookings.html
{% extends 'web/base.html' %} {% block content %}
{% load static %}
<!-- main -->
<main class="main bg-white h-100 " id="top" >

      <div class="row text-center mx-3">
        <h4 class="section-title-purple mt-5">我的需求列表</h4>
      </div>
      {% for order in orders %}
      <div class="row mt-4">
       
        <div class="col-10 col-sm-10 col-md-9 col-lg-8 col-xl-7 mx-auto ">

         <div class="custom-card">
          
          <div class="row">
             
            <div class="d-none d-md-block col-md-3 col-lg-3 col-xl-2">
              <div class="green-border-tag mt-2 ">{% if order.state == 'PAID' %}已付款{% elif order.state == 'UNPAID' %}未付款{% else %}已取消{% endif %}</div>
              <div class="purple-border-tag mt-2">{% if order.case.care_type == 'home' %}居家照顧{% else %}醫院看護{% endif %}</div>
            </div>

            <div class="d-block d-md-none ">
              <div class="green-border-tag mt-2" style="display: inline-block;">未完成</div>
              <div class="purple-border-tag mt-2" style="display: inline-block;">醫院看護</div>
            </div>

            <div class="col-md-6 col-lg-6 col-xl-8">
              <p class="custom-card-font mt-2">
                {{order.case.start_datetime.year}}/{{order.case.start_datetime.month}}/{{order.case.start_datetime.day}} ~ {{order.case.end_datetime.year}}/{{order.case.end_datetime.month}}/{{order.case.end_datetime.day}} <br> 
                時間類型：{% if order.case.is_continuous_time == True %}連續時間{% else %}指定時段{% endif %}  <br>
                照顧者：{{order.servant.name}} <br>
                地點：{{order.case.city}} 
              </p>
            </div>

            <div class="col-sm-5 col-md-3 col-lg-2 col-xl-2 align-self-center">
              <a href="{% url 'my_booking_detail' %}?order={{order.id}}">
                <button class="small-purple-button">查看訂單</button>
              </a>
            </div>

          </div>

         </div>

        </div>
        
      </div>
      {% endfor %}

     
</main>
{% endblock %}

app/web/templates/web/my/cases.html
{% extends 'web/base.html' %} {% block content %}
{% load static %}
<!-- main -->
<main class="main bg-white h-100 " id="top" >

      <div class="row text-center mx-3">
        <h4 class="section-title-purple mt-5">我的接案</h4>
      </div>
      {% for case in cases %}
      <div class="row mt-4">
       
        <div class="col-10 col-sm-10 col-md-9 col-lg-8 col-xl-7 mx-auto ">

         <div class="custom-card">
          
          <div class="row">
             
            <div class="d-none d-md-block col-md-3 col-lg-3 col-xl-2">
              <div class="green-border-tag mt-2 ">{% if case.state == 'unComplete' %}未完成{% elif case.state == 'unTaken' %}未承接{% elif case.state == 'Complete' %}已完成{% elif case.state == 'Canceled' %}取消{% else %}提早完成{% endif %}</div>
              <div class="purple-border-tag mt-2">{% if case.care_type == 'home' %}居家照顧{% else %}醫院看護{% endif %}</div>
            </div>

            <div class="d-block d-md-none ">
              <div class="green-border-tag mt-2" style="display: inline-block;">未完成</div>
              <div class="purple-border-tag mt-2" style="display: inline-block;">醫院看護</div>
            </div>

            <div class="col-md-6 col-lg-6 col-xl-8">
              <p class="custom-card-font mt-2">
                {{case.start_datetime.year}}/{{case.start_datetime.month}}/{{case.start_datetime.day}} ~ {{case.end_datetime.year}}/{{case.end_datetime.month}}/{{case.end_datetime.day}} <br> 
                時間類型：{% if case.is_continuous_time == True %}連續時間{% else %} 指定時段{% endif %} <br>
                地點：{{case.city}} <br>
                案主評價：{% if review.servant_comment %}{{review.servant_comment}}{% else %}案主尚未評價{% endif %}
              </p>
            </div>

            <div class="col-sm-5 col-md-3 col-lg-2 col-xl-2 align-self-center">
              <a href="{% url 'my_case_detail' %}?case={{case.id}}">
                <button class="small-purple-button">案件詳情</button>
              </a>
              <a href="{% url 'my_simplfy_certificate' %}?case={{case.id}}">
                <button class="small-purple-button mt-2">看護證明</button>
              </a>
              
            </div>

          </div>

         </div>

        </div>
        
      </div>
      {% endfor %}

     
</main>
{% endblock %}

app/web/templates/web/my/my_service_setting_about.html
{% extends 'web/base.html' %} {% block content %}
{% load static %}
<!-- main -->
<main class="main bg-white" id="top" >

      <div class="row text-center mx-3">
        <h4 class="section-title-purple mt-5">我的服務設定</h4>
      </div>

      <!-- tab -->
      <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="row">
          <div class="col-10 col-sm-7 col-md-6 col-lg-4 col-xl-4 mx-auto">
            <ul class="nav custom-nav-tabs mt-2" id="myTab" role="tablist">
              <li class="nav-item mx-auto"><a class="nav-link" href="{% url 'my_service_setting_time' %}">時段語言</a></li>
              <li class="nav-item mx-auto"><a class="nav-link" href="{% url 'my_service_setting_services' %}">服務項目</a></li>
              <li class="nav-item mx-auto"><a class="nav-link active" href="{% url 'my_service_setting_about' %}">關於我</a></li>
            </ul>
          </div>
        </div>

        <div class="row">
          <div class="col-12 col-sm-10 col-md-9 col-lg-8 col-xl-7 mx-auto mt-3">
            <div class="p-3 mt-3" >
              <!-- tab 關於我 -->              
                <p class="custom-card-font mt-3"><strong>相關文件</strong></p>
                <div>
                  {% for licenseImageShip in licenseImageShips %}   
                  
                    <form method="post" id="license_{{licenseImageShip.license.id}}_post" enctype="multipart/form-data">{% csrf_token %}
                    
                        <div class="row mt-2 justify-content-between">

                          <div class="col-sm-12 col-md-4 align-self-center">
                            <span class="h6">
                              {{licenseImageShip.license}}
                              {% if licenseImageShip.license.remark %}
                                <br><span class="sub-font">{{licenseImageShip.license.remark}}</span>
                              {% endif %}
                              {% if licenseImageShip.isPassed %}
                                <br>
                                {% if licenseImageShip.image %}
                                  <a href={{licenseImageShip.image.url}} > 文件圖片連結 </a>
                                {% endif %}
                                (通過審核)
                              {% else %}
                                <br>
                                {% if licenseImageShip.image %}
                                  <a href={{licenseImageShip.image.url}} > 文件圖片連結 </a>
                                {% endif %}
                                (尚未通過審核)
                              {% endif %}
                            </span>
                          </div>
  
                          <div class="col-sm-12 col-md-8 align-self-center">
                              
                                <input type="hidden" id="licenseId" name="licenseId" value="{{licenseImageShip.license.id}}">
                                <input type="hidden" id="userId" name="userId" value={{user}}>
                                {{ form.user.as_hidden }}
                                <div class="d-flex justify-content-end">
                                  <div class="text-end">
                                    <!-- 原本的 choose file -->
                                    <div id="form-container" type="hidden">
                                      <input type="file" name="image" accept="image/*" id="id_{{licenseImageShip.license.id }}_image"  style="padding-right: 0; margin-right: 0;">
                                    </div>
                                    
                                    
                                    <!-- 美化過的 choose file -->
                                    <!-- <label class="btn btn-info rounded-pill">
                                      <input type="file" name="image" accept="image/*" id="id_image" style="display:none;">
                                      選擇圖片
                                    </label> -->
                                    <!--  If you want to display the file name, you need to add a span between the label and the hidden input: 
                                    <span id="file-selected"></span>. 
                                    Then update the span on the change event: 
                                    $('#file-upload').bind('change', function() { var fileName = ''; fileName = $(this).val(); $('#file-selected').html(fileName); }) -->
  
                                  </div>
                                  <div class="text-end">
                                    <button class="small-purple-button" type="button" id="license_{{licenseImageShip.license.id }}_image_submit" ><span class="fas fa-cloud-upload-alt"></span> 上傳</button>
                                  </div>
                                </div>                               
                          </div> 
                        </div>                  
                      <hr>
                    </form>
                  {% endfor %}
                </div>


                <p class="custom-card-font mt-5"><strong>關於我</strong><span> *確保會員權益請勿填寫個人聯絡方式</span></p>
                
                <p class="custom-card-font mt-5"><strong>關於我</strong></p>
                <textarea class="custom-form-control" id="exampleFormControlTextarea1" name="about_me" rows="3">{{user.about_me}}</textarea>
                
                <div>
                  <form method="post" id="background_image_post" enctype="multipart/form-data">{% csrf_token %}
                    
                    <div class="row mt-5 justify-content-between">

                      <div class="col-sm-12 col-md-4 align-self-center">
                    
                      <span class="custom-card-font">
                        <strong>上傳背景照片 </strong>
                        {% if user.background_image %}
                          <br><a href={{user.background_image.url}} > 背景圖片連結 </a>
                        {% endif %}
                      </span>
                      
                      </div>

                      <div class="col-sm-12 col-md-8 text-end align-self-center">
                        <div class="d-flex justify-content-end">

                        <div class="me-2">
                          <input type="hidden" id="userId" name="userId" value={{user.phone}}>
                          {{ userform.as_hidden }}
                          <div id="form2-container" type="hidden">
                            <input type="file" name="background_image" accept="image/*" id="id_background_image">
                          </div>
                          
                        </div>
  
                        <div class="text-end">
                          <button class="small-purple-button" id="backgroundImageBtn" type="button" ><span class="fas fa-cloud-upload-alt"></span> 上傳</button>
                        </div>
  
                        </div>
                      </div>
                    </div>
                    
                  </form>
                  <span>* 確保會員權益請勿上傳個人聯絡方式之圖片</span>
                </div>

                <div class="col-4 mt-7 mx-auto text-center">
                  <button class="full-purple-button" type="submit" >儲存</button>
                </div>
            </div>
          </div>
        </div>
      </form>
     <script>
      const licenseImageCount = Number("{{licenseImageShips|length}}") + 3
      $( document ).ready(function() {
        for (var i = 4; i <= licenseImageCount; i++){
        const license_image_submit = document.getElementById('license_'+String(i)+'_image_submit');
        const id_image = document.getElementById('id_'+String(i)+'_image');
        const form_submit = document.getElementById('license_'+String(i)+'_post')
        license_image_submit.addEventListener('click',function(){
          console.log('click')
          id_image.click();
        });
        // function upload_license_image(){
        //   // id_image_name = id_image.id;
        //   // num = id_image_name.split('id_')[1].split('_image')[0];
        //   // console.log(num);
        //   // document.getElementById('license_'+String(i)+'_post').submit();
        // }
        id_image.addEventListener("change",function(){
          form_submit.submit();
        });
      }
      });
      
      const backgroundImageBtn = document.getElementById('backgroundImageBtn');
      const id_background_image = document.getElementById('id_background_image');
      const background_image_post = document.getElementById('background_image_post');

      backgroundImageBtn.addEventListener('click',function(){
        id_background_image.click();
      })
      id_background_image.addEventListener('change',function(){
        background_image_post.submit();
      });

     </script>
</main>
{% endblock %}